### ISSUE TITLE
Segmentation fault in Gobby 0.5.0. Certificate related?

### ISSUE THREAD

**Issue by JohnCC330** [gobby/gobby#127]
I recompiled and reinstalled libinfinity, and a series of undefined symbols in in libgnutls were reported. First, I compiled and installed a newer version of the p11, then did the same for libgnutls. Finally, i reinstalled libinfinity (0.7.0), and gobby (0.5.0). This is the result:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff1c03060 in __memcpy_sse2_unaligned () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff1c03060 in __memcpy_sse2_unaligned () from /lib64/libc.so.6
#1  0x00007ffff2a57f16 in _asn1_set_value (node=node@entry=0xad09f0, value=0x2f53555f6e652f65, len=1298088780)
    at parser_aux.c:245
#2  0x00007ffff2a59405 in _asn1_copy_structure3 (source_node=0x812180) at structure.c:417
#3  0x00007ffff2a5c05e in asn1_der_coding (element=<optimized out>, name=<optimized out>, ider=0x0, 
    len=0x7fffffffbd10, ErrorDescription=0x0) at coding.c:1029
#4  0x00007ffff29de67d in _gnutls_x509_der_encode (src=0x812180, src_name=0x7ffff2a6bea9 "", res=0x7fffffffbda0, 
    str=str@entry=0) at common.c:1255
#5  0x00007ffff29de936 in _gnutls_x509_export_int_named2 (asn1_data=<optimized out>, name=<optimized out>, 
    format=<optimized out>, pem_header=<optimized out>, out=<optimized out>) at common.c:1004
#6  0x00007ffff29dea4c in _gnutls_x509_export_int_named (asn1_data=<optimized out>, name=<optimized out>, 
    format=GNUTLS_X509_FMT_DER, pem_header=<optimized out>, output_data=0x0, output_data_size=0x7fffffffbde8)
    at common.c:961
#7  0x00007ffff2a085dd in _gnutls_x509_crt_cpy (dest=0xac3e70, src=0x7ee910) at x509.c:116
#8  0x00007ffff29c0a64 in gnutls_certificate_set_x509_trust (res=0xac3de0, ca_list=<optimized out>, 
    ca_list_size=151) at gnutls_x509.c:1557
#9  0x000000000047c1d0 in Gobby::CertificateManager::make_credentials (this=this@entry=0x7fffffffc750)
    at certificatemanager.cpp:442
#10 0x000000000047d17e in Gobby::CertificateManager::load_trust (this=this@entry=0x7fffffffc750)
    at certificatemanager.cpp:388
#11 0x000000000047d585 in Gobby::CertificateManager::CertificateManager (this=0x7fffffffc750, preferences=...)
    at certificatemanager.cpp:53
#12 0x000000000042422e in main (argc=1, argv=0x7fffffffdd58) at main.cpp:287
```
When running gobby alone (outside gdb), I only get the segfault. Running inside gdb, I also get a few warnings:

```
warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7ffff7ffa000
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib64/libgobject-2.0.so.0.4508.0-gdb.py", line 9, in <module>
    from gobject import register
  File "/usr/share/glib-2.0/gdb/gobject.py", line 117, in <module>
    class SignalFrame(FrameDecorator):
NameError: name 'FrameDecorator' is not defined
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

```
The first 2 warnings might be due to a bug in gdb which has been solved recently.

**Comment by aburgm** [comment]
libinfinity 0.7.0 (which was not released yet, so I assume this corresponds to the master branch of the libinfinity repo?) and gobby 0.5.0 don't go together. Gobby 0.5.0 will use libinfinity 0.6.x. So if there is some binary incompatibility with respect to gnutls, I would first suggest trying to rebuild libinfinity 0.6.x against the version of gnutls that you have updated to.

**Comment by JohnCC330** [comment]
Thanks for the correction! I installed 0.6.7, and all was well.
On the other hand, libinfinity-master configured and built without problems against gnutls 3.4.9, this was a run-time problem. So maybe the issue does merit a closer look before releasing 0.7.

Generally, thanks for all the good work!
