### ISSUE TITLE
Crash trying to reconnect

### ISSUE THREAD

**Issue by traumschule** [gobby/gobby#175]
Hi! Thanks for this nice program, it is still useful and works well with infinoted 0.7.1 in combination with tor to provide an onion service.

Gobby 0.6.0 lost the connection, trying to reconnect it crashed.
```
(gobby:26506): Gtk-WARNING **: 16:55:00.898: Theme parsing error: <data>:6:28: The style property GtkWidget:focus-padding is deprecated and shouldn't be used anymore. It will be removed in a future version
**
ERROR:common/inf-xmpp-connection.c:3403:inf_xmpp_connection_notify_status_cb: assertion failed: (priv->status == INF_XMPP_CONNECTION_CONNECTING)
Aborted
```
Trying to reproduce it with gdb to get a trace.

**Comment by traumschule** [comment]
```
[New Thread 0xaf0ffb40 (LWP 32207)]                                              
[Thread 0xaf0ffb40 (LWP 32207) exited]                                                   
                                                              
1547646945 ERROR torsocks[27980]: Connection timed out (in socks5_recv_connect_reply() at socks5.c:547)
                                                                    
** (gobby:27980): WARNING **: 08:55:45.282: Failed to reconnect: Connection timed out            
                                                                    
**                                                                                      
ERROR:common/inf-xmpp-connection.c:3403:inf_xmpp_connection_notify_status_cb: assertion failed: (priv->status == INF_XMPP_CONNECTION_CONNECT
ING)                                                          
1547652360 WARNING torsocks[27975]: [syscall] Unsupported syscall number 238. Denying the call (in tsocks_syscall() at syscall.c:568)
                                                                    
[1]+  Stopped                 torsocks gdb gobby                                        
data@debian:~$                                                                   
data@debian:~$ fg                                             
torsocks gdb gobby                                            
tkill: Function not implemented.                              
(gdb) bt                                                        
#0  0xb7fd4cf9 in __kernel_vsyscall ()                                                                                                      
#1  0xb5e572d2 in __libc_signal_restore_set (set=0xbfffdd3c)
    at ../sysdeps/unix/sysv/linux/internal-signals.h:84
#2  0xb5e572d2 in __GI_raise (sig=6) at ../sysdeps/unix/sysv/linux/raise.c:48
#3  0xb5e412b6 in __GI_abort () at abort.c:79
#4  0xb642adc4 in  () at /usr/lib/i386-linux-gnu/libglib-2.0.so.0
#5  0xb6486edc in g_assertion_message_expr () at /usr/lib/i386-linux-gnu/libglib-2.0.so.0
#6  0xb62f536c in  () at /usr/lib/i386-linux-gnu/libinfinity-0.7.so.0
#7  0xb655c0e8 in g_closure_invoke () at /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#8  0xb656fbf2 in  () at /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#9  0xb6578f17 in g_signal_emit_valist () at /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#10 0xb65794b5 in g_signal_emit () at /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#11 0xb6560397 in  () at /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#12 0xb655fc45 in  () at /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#13 0xb6562b9d in g_object_thaw_notify () at /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#14 0xb62ee22f in  () at /usr/lib/i386-linux-gnu/libinfinity-0.7.so.0
#15 0xb62ee87e in  () at /usr/lib/i386-linux-gnu/libinfinity-0.7.so.0
#16 0xb62ee3e7 in  () at /usr/lib/i386-linux-gnu/libinfinity-0.7.so.0
#17 0xb62f4823 in  () at /usr/lib/i386-linux-gnu/libinfinity-0.7.so.0
#18 0xb63e5427 in  () at /usr/lib/i386-linux-gnu/libinfgtk-0.7.so.0
#19 0xb655c0e8 in g_closure_invoke () at /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#20 0xb656f42d in  () at /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#21 0xb6578f17 in g_signal_emit_valist () at /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#22 0xb65794b5 in g_signal_emit () at /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#23 0xb6e3df31 in gtk_tree_view_row_activated () at /usr/lib/i386-linux-gnu/libgtk-3.so.0
#24 0xb6e4811e in  () at /usr/lib/i386-linux-gnu/libgtk-3.so.0
#25 0xb316210e in ffi_call_SYSV () at /usr/lib/i386-linux-gnu/libffi.so.6
#26 0xb3161d9c in ffi_call () at /usr/lib/i386-linux-gnu/libffi.so.6
#27 0xb655cc80 in g_cclosure_marshal_generic_va () at /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#28 0xb655c30c in  () at /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#29 0xb6578fac in g_signal_emit_valist () at /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#30 0xb65794b5 in g_signal_emit () at /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#31 0xb6cbfcee in  () at /usr/lib/i386-linux-gnu/libgtk-3.so.0
#32 0xb655ef05 in g_cclosure_marshal_VOID__BOXEDv () at /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#33 0xb655c30c in  () at /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#34 0xb6578fac in g_signal_emit_valist () at /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#35 0xb65794b5 in g_signal_emit () at /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#36 0xb6cbc8b5 in  () at /usr/lib/i386-linux-gnu/libgtk-3.so.0
#37 0xb6cbded8 in  () at /usr/lib/i386-linux-gnu/libgtk-3.so.0
#38 0xb6cc1078 in  () at /usr/lib/i386-linux-gnu/libgtk-3.so.0
#39 0xb6c86bab in gtk_event_controller_handle_event () at /usr/lib/i386-linux-gnu/libgtk-3.so.0
#40 0xb6e5710e in  () at /usr/lib/i386-linux-gnu/libgtk-3.so.0
#41 0xb63e584a in  () at /usr/lib/i386-linux-gnu/libinfgtk-0.7.so.0
#42 0xb6eb0748 in  () at /usr/lib/i386-linux-gnu/libgtk-3.so.0
#43 0xb655c30c in  () at /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#44 0xb65789ff in g_signal_emit_valist () at /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#45 0xb65794b5 in g_signal_emit () at /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#46 0xb6e5966f in  () at /usr/lib/i386-linux-gnu/libgtk-3.so.0
#47 0xb6d099e0 in  () at /usr/lib/i386-linux-gnu/libgtk-3.so.0
#48 0xb6d0be8a in gtk_main_do_event () at /usr/lib/i386-linux-gnu/libgtk-3.so.0
#49 0xb69f65c7 in  () at /usr/lib/i386-linux-gnu/libgdk-3.so.0
#50 0xb6a29ad7 in  () at /usr/lib/i386-linux-gnu/libgdk-3.so.0
#51 0xb645ed4d in g_main_context_dispatch () at /usr/lib/i386-linux-gnu/libglib-2.0.so.0
#52 0xb645f009 in  () at /usr/lib/i386-linux-gnu/libglib-2.0.so.0
#53 0xb645f0b4 in g_main_context_iteration () at /usr/lib/i386-linux-gnu/libglib-2.0.so.0
#54 0xb6677673 in g_application_run () at /usr/lib/i386-linux-gnu/libgio-2.0.so.0
#55 0xb7591b29 in Gio::Application::run(int, char**) () at /usr/lib/i386-linux-gnu/libgiomm-2.4.so.1
#56 0x0043d6c3 in main(int, char**) (argc=1, argv=0xbffff634) at code/main.cpp:25
```
